# Generated by Django 5.2.5 on 2025-10-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='From Email'),
        ),
    ]
