# Generated by Django 5.2.5 on 2025-09-15 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='New Chat', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_response_metadata', models.JSONField(blank=True, null=True)),
                ('ai_references', models.JSONField(blank=True, null=True)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['-last_activity'], name='chat_chat_last_ac_6a2607_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', '-created_at'], name='chat_chat_user_id_d9308c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', '-created_at'], name='chat_messag_chat_id_013eed_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['role', '-created_at'], name='chat_messag_role_a821ce_idx'),
        ),
    ]
