# Generated by Django 5.2.5 on 2025-10-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='selected_model',
            field=models.CharField(blank=True, help_text='The AI model selected by the user for this message', max_length=100, null=True),
        ),
    ]
